language: python

install:
  - pip install tox

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
# - TOX_ENV=py35
  - TOX_ENV=pypy

script:
  - tox -e $TOX_ENV

matrix:
  fast_finish: true

  include:
    # https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-143758799
    - python: 3.5
      env:
      - TOX_ENV=py35
